version: 2

builds:
  - main: .
    binary: forge
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/alternayte/forge/internal/cli.Version={{ .Tag }}
      - -X github.com/alternayte/forge/internal/cli.Commit={{ .ShortCommit }}
      - -X github.com/alternayte/forge/internal/cli.Date={{ .Date }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
